"""created stream config

Revision ID: 042dcafad16f
Revises: 61c6023bf0d0
Create Date: 2025-07-20 17:59:34.581936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042dcafad16f'
down_revision: Union[str, Sequence[str], None] = '61c6023bf0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clip_duration', sa.Float(), nullable=False),
    sa.Column('window_timespan', sa.Float(), nullable=False),
    sa.Column('sample_interval', sa.Integer(), nullable=False),
    sa.Column('baseline_duration', sa.Integer(), nullable=False),
    sa.Column('surge_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_config_id'), 'stream_config', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_config_id'), table_name='stream_config')
    op.drop_table('stream_config')
    # ### end Alembic commands ###
