"""added updated_at column

Revision ID: 0aa2f71f8fbe
Revises: 6a44f53d90e5
Create Date: 2025-07-19 19:36:35.443231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa2f71f8fbe'
down_revision: Union[str, Sequence[str], None] = '6a44f53d90e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_clips_processes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream_clips_processes', 'updated_at')
    # ### end Alembic commands ###
