"""streamer is_active field

Revision ID: 88e536e3fae6
Revises: 1a457d79443a
Create Date: 2025-07-14 16:57:19.819463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88e536e3fae6'
down_revision: Union[str, Sequence[str], None] = '1a457d79443a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamers', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamers', 'is_active')
    # ### end Alembic commands ###
