"""instances

Revision ID: a7f93772c39f
Revises: 042dcafad16f
Create Date: 2025-07-20 21:32:13.925110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f93772c39f'
down_revision: Union[str, Sequence[str], None] = '042dcafad16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('max_processes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('hostname')
    )
    op.add_column('stream_clips_processes', sa.Column('instance_hostname', sa.String(), nullable=False))
    op.create_foreign_key(None, 'stream_clips_processes', 'instances', ['instance_hostname'], ['hostname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stream_clips_processes', type_='foreignkey')
    op.drop_column('stream_clips_processes', 'instance_hostname')
    op.drop_table('instances')
    # ### end Alembic commands ###
