"""last_activity

Revision ID: db3bf33f5aa6
Revises: f45fd776cabe
Create Date: 2025-07-23 15:01:27.730061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3bf33f5aa6'
down_revision: Union[str, Sequence[str], None] = 'f45fd776cabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_clips_processes', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream_clips_processes', 'last_activity')
    # ### end Alembic commands ###
