"""stream clips processes

Revision ID: f03b01211783
Revises: 88e536e3fae6
Create Date: 2025-07-14 20:17:26.700927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03b01211783'
down_revision: Union[str, Sequence[str], None] = '88e536e3fae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_clips_processes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('streamer_id', sa.UUID(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_clips_processes_id'), 'stream_clips_processes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_clips_processes_id'), table_name='stream_clips_processes')
    op.drop_table('stream_clips_processes')
    # ### end Alembic commands ###
