"""add last_processed_at to streamers

Revision ID: f45fd776cabe
Revises: 6c454b368065
Create Date: 2025-07-22 17:28:16.722992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45fd776cabe'
down_revision: Union[str, Sequence[str], None] = '6c454b368065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamers', sa.Column('last_processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamers', 'last_processed_at')
    # ### end Alembic commands ###
